// AUTO-GENERATED by scripts/gen-products.mjs — do not edit by hand.
import type { Product } from './types';

export const USD_TO_KRW = 1350;

export const products: Product[] = [
  {
    "id": 17,
    "name": "퍼플렉시티(Perplexity)",
    "brand": "Perplexity",
    "category": "ai",
    "fromUsd": 1.72,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 6.39
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 12.59
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 22.99
      }
    ],
    "maxShare": 6,
    "features": [
      "출처 링크와 함께 직접 답변하는 AI 검색엔진",
      "질문만 입력하면 정확한 답변 제공",
      "다양한 자연어 작업 지원"
    ],
    "icon": "/icons/17.webp"
  },
  {
    "id": 21,
    "name": "제미나이(Gemini)",
    "brand": "Gemini",
    "category": "ai",
    "fromUsd": 2.12,
    "skus": [
      {
        "label": "12 months",
        "months": 12,
        "usd": 29.99
      }
    ],
    "maxShare": 1,
    "features": [
      "구글 Gemini Pro 공식 계정 (최신 모델)",
      "4K 초고화질 이미지 즉시 생성",
      "구매 즉시 자동 활성화·로그인 제공"
    ],
    "icon": "/icons/21.webp"
  },
  {
    "id": 7,
    "name": "ChatGPT Plus",
    "brand": "ChatGPT Plus",
    "category": "ai",
    "fromUsd": 4.5,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 15.59
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 30.69
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 59.99
      }
    ],
    "maxShare": 6,
    "features": [
      "공식 4.0 모델",
      "GPT 스토어 즐기기",
      "플러그인 사용 가능",
      "API 금지"
    ],
    "icon": "/icons/7.png"
  },
  {
    "id": 14,
    "name": "감마(Gamma)",
    "brand": "Gamma",
    "category": "ai",
    "fromUsd": 4.93,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 18.88
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 32.88
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 63.99
      }
    ],
    "maxShare": 6,
    "features": [
      "Gamma Pro 패키지, 무제한 AI 제작",
      "높은 완성도와 정교한 디테일 제어",
      "Flux Ultra·Ideogram·DALL·E 3 등 프리미엄 이미지 생성"
    ],
    "icon": "/icons/14.webp"
  },
  {
    "id": 26,
    "name": "그래머리(Grammarly)",
    "brand": "Grammarly",
    "category": "ai",
    "fromUsd": 4.99,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 13.99
      }
    ],
    "maxShare": 1,
    "features": [
      "영어 글쓰기 품질을 높이는 AI 어시스턴트",
      "문법·맞춤법·어조 분석 및 리포트",
      "실시간 오류·개선 제안 피드백"
    ],
    "icon": "/icons/26.webp"
  },
  {
    "id": 29,
    "name": "비드IQ(vidIQ)",
    "brand": "vidIQ",
    "category": "ai",
    "fromUsd": 8.99,
    "skus": [
      {
        "label": "1 month",
        "months": 1,
        "usd": 9.99
      }
    ],
    "maxShare": 1,
    "features": [
      "유튜브 조회수·노출 최적화 키워드 분석",
      "AI로 영상 아이디어·태그·제목 생성",
      "트렌드 분석과 맞춤 채널 코칭"
    ],
    "icon": "/icons/29.webp"
  },
  {
    "id": 22,
    "name": "그록(Grok)",
    "brand": "Grok",
    "category": "ai",
    "fromUsd": 10.34,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 38.99
      },
      {
        "label": "6 months",
        "months": 5,
        "usd": 72.99
      }
    ],
    "maxShare": 3,
    "features": [
      "최신 Grok 4.1 지원, 더 빠르고 똑똑한 AI",
      "고빈도 질의 및 이미지 생성",
      "DeepSearch·Think 모드로 복잡한 문제 해결"
    ],
    "icon": "/icons/22.webp"
  },
  {
    "id": 2,
    "name": "스포티파이",
    "brand": "Spotify",
    "category": "streaming",
    "fromUsd": 2.3,
    "skus": [
      {
        "label": "3 months(personal)",
        "months": 3,
        "usd": 16.99
      },
      {
        "label": "12 months(personal)",
        "months": 12,
        "usd": 42.99
      }
    ],
    "maxShare": 5,
    "features": [
      "프리미엄 플랜, $2.55/월/스크린",
      "충실도 높은 사운드",
      "실시간 배송",
      "모바일, PC, 탭"
    ],
    "icon": "/icons/2.webp"
  },
  {
    "id": 3,
    "name": "디즈니플러스",
    "brand": "Disney+",
    "category": "streaming",
    "fromUsd": 2.53,
    "skus": [
      {
        "label": "1 month",
        "months": 1,
        "usd": 5.69
      },
      {
        "label": "3 months",
        "months": 3,
        "usd": 12.89
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 21.89
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 31.99
      }
    ],
    "maxShare": 7,
    "features": [
      "프리미엄 플랜, $2.1/월/스크린",
      "6명이 1구독을 공유하고,",
      "모바일, PC, TV",
      "개인 프로필 및 기록"
    ],
    "icon": "/icons/3.png"
  },
  {
    "id": 8,
    "name": "크런치롤",
    "brand": "Crunchyroll",
    "category": "streaming",
    "fromUsd": 2.54,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 8.88
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 16.99
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 32.98
      }
    ],
    "maxShare": 4,
    "features": [
      "4명이 구독 1개를 공유합니다.",
      "실시간 배송",
      "모바일 단말기, PC, TV, TV 박스 지원",
      "애프터 서비스 지원, 걱정 없는 환불"
    ],
    "icon": "/icons/8.png"
  },
  {
    "id": 9,
    "name": "타이달",
    "brand": "Tidal",
    "category": "streaming",
    "fromUsd": 2.69,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 9.69
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 18.69
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 38.99
      }
    ],
    "maxShare": 5,
    "features": [
      "1억 1천만+ 무손실·HiRes FLAC·돌비 애트모스",
      "광고 없는 HIFI 전곡 감상, 오프라인 재생",
      "여러 기기 간 음악·플레이리스트 동기화"
    ],
    "icon": "/icons/9.png"
  },
  {
    "id": 27,
    "name": "디저(Deezer)",
    "brand": "Deezer",
    "category": "streaming",
    "fromUsd": 2.99,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 9.59
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 18.59
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 35.99
      }
    ],
    "maxShare": 5,
    "features": [
      "광고 없는 무제한 음악 감상",
      "오프라인 다운로드 재생",
      "FLAC 최대 1411kbps 고음질"
    ],
    "icon": "/icons/27.webp"
  },
  {
    "id": 5,
    "name": "유튜브 프리미엄",
    "brand": "YouTube Premium",
    "category": "streaming",
    "fromUsd": 3.57,
    "skus": [
      {
        "label": "6 months",
        "months": 6,
        "usd": 27.59
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 47.59
      }
    ],
    "maxShare": 5,
    "features": [
      "프리미엄 요금제, $3.88/월/스크린",
      "실시간으로 초대 링크 보내기",
      "개인 구독, 모든 즐겨찾기 및 목록 유지",
      "보증, 환불 보증"
    ],
    "icon": "/icons/5.webp"
  },
  {
    "id": 1,
    "name": "넷플릭스",
    "brand": "Netflix",
    "category": "streaming",
    "fromUsd": 5.39,
    "skus": [
      {
        "label": "1 month",
        "months": 1,
        "usd": 5.99
      }
    ],
    "maxShare": 5,
    "features": [
      "프리미엄 요금제, $3.69/월/화면",
      "5명이 구독 1개 공유",
      "모바일, PC, TV",
      "4K, HDR, 돌비"
    ],
    "icon": "/icons/1.webp"
  },
  {
    "id": 12,
    "name": "듀오링고",
    "brand": "Duolingo",
    "category": "creator",
    "fromUsd": 1.45,
    "skus": [
      {
        "label": "6 months",
        "months": 6,
        "usd": 13.99
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 19.99
      }
    ],
    "maxShare": 5,
    "features": [
      "슈퍼 듀오링고를 즐기세요",
      "회원은 광고 없는 학습 환경을 누릴 수 있어, 각 수업 종료 시 광고 방해를 피하고 집중해서 공부할 수 있습니다",
      "'맞춤형 연습' 기능을 사용하여 연습 중에 발생하는 오류를 교정하세요",
      "회원은 고급 전설 레벨에 무제한으로 도전하여, 배운 내용을 심도 있게 숙달하고 언어 능력을 향상시킬 수 있습니다"
    ],
    "icon": "/icons/12.png"
  },
  {
    "id": 28,
    "name": "픽시브(pixiv)",
    "brand": "pixiv",
    "category": "creator",
    "fromUsd": 1.66,
    "skus": [
      {
        "label": "12 months",
        "months": 12,
        "usd": 18.99
      }
    ],
    "maxShare": 1,
    "features": [
      "pixiv 프리미엄 광고 없는 빠른 탐색",
      "고급 검색·열람기록·즐겨찾기 정리",
      "작품 예약 게시·성과 분석"
    ],
    "icon": "/icons/28.webp"
  },
  {
    "id": 15,
    "name": "오피스 365",
    "brand": "Office 365",
    "category": "creator",
    "fromUsd": 1.95,
    "skus": [
      {
        "label": "12 months",
        "months": 12,
        "usd": 35.99
      }
    ],
    "maxShare": 5,
    "features": [
      "Word·Excel·PowerPoint·Outlook·Teams 전체 앱",
      "PC·모바일·태블릿 동기화",
      "1TB 클라우드 저장공간 포함"
    ],
    "icon": "/icons/15.png"
  },
  {
    "id": 11,
    "name": "캔바(Canva)",
    "brand": "Canva",
    "category": "creator",
    "fromUsd": 2.99,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 15.99
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 29.99
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 56.99
      }
    ],
    "maxShare": 3,
    "features": [
      "브랜드 색상, 글꼴, 로고 등을 포함한 브랜드 키트를 생성 및 저장하여 모든 디자인의 일관성을 보장하세요",
      "1TB 클라우드 스토리지 – 모든 설정 자료가 클라우드에 업로드 및 저장되므로 저장 공간 부족을 걱정할 필요가 없습니다",
      "수백만 개의 디자인 템플릿, 사진, 일러스트, 아이콘, 오디오, 비디오 및 애니메이션",
      "20개 이상의 AI 도구를 활용하여 창의력을 자극하세요"
    ],
    "icon": "/icons/11.png"
  },
  {
    "id": 20,
    "name": "노션(Notion)",
    "brand": "Notion",
    "category": "creator",
    "fromUsd": 3.08,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 8.59
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 16.59
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 29.99
      }
    ],
    "maxShare": 1,
    "features": [
      "Notion Plus 요금제 올인원 워크스페이스",
      "문서·위키·프로젝트 통합 관리",
      "실시간 협업 지원"
    ],
    "icon": "/icons/20.webp"
  },
  {
    "id": 19,
    "name": "UPDF",
    "brand": "UPDF",
    "category": "creator",
    "fromUsd": 3.32,
    "skus": [
      {
        "label": "1 month",
        "months": 3,
        "usd": 4.68
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 23.59
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 47.99
      }
    ],
    "maxShare": 3,
    "features": [
      "UPDF Pro + AI 문서 자동화",
      "스캔 문서를 편집 가능한 PDF로 (OCR)",
      "다양한 포맷 변환·비밀번호 보호"
    ],
    "icon": "/icons/19.webp"
  },
  {
    "id": 16,
    "name": "캡컷(CapCut)",
    "brand": "CapCut",
    "category": "creator",
    "fromUsd": 6.6,
    "skus": [
      {
        "label": "1 month",
        "months": 1,
        "usd": 7.99
      },
      {
        "label": "6 months",
        "months": 6,
        "usd": 44.59
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 87.99
      }
    ],
    "maxShare": 1,
    "features": [
      "캡컷 Pro 전체 기능 (팀 플랜)",
      "4K·HDR 고화질 내보내기",
      "배경제거·자동자막 등 AI 편집 도구"
    ],
    "icon": "/icons/16.webp"
  },
  {
    "id": 24,
    "name": "어도비(Adobe)",
    "brand": "Adobe",
    "category": "creator",
    "fromUsd": 11.99,
    "skus": [
      {
        "label": "3 months",
        "months": 3,
        "usd": 36.99
      },
      {
        "label": "12 months",
        "months": 12,
        "usd": 143.99
      }
    ],
    "maxShare": 1,
    "features": [
      "Photoshop·Premiere·After Effects 등 전 앱",
      "기기 간 클라우드 저장·동기화",
      "생성형 AI 크레딧 포함"
    ],
    "icon": "/icons/24.webp"
  },
  {
    "id": 13,
    "name": "유튜브 충전",
    "brand": "YouTube Recharge",
    "category": "etc",
    "fromUsd": 3.67,
    "skus": [
      {
        "label": "3 months⚡(Own account, in 12hrs)",
        "months": 3,
        "usd": 14.99
      }
    ],
    "maxShare": 1,
    "features": [
      "주문 후에는 환불이 불가합니다.",
      "YouTube Premium을 이용 중인 계정은 현재 충전이 지원되지 않습니다.",
      "구매 후 충전은 개인 계정에 적용되며, 안전하고 안정적입니다!",
      "재생목록과 구독 정보는 그대로 유지됩니다."
    ],
    "icon": "/icons/13.png"
  },
  {
    "id": 30,
    "name": "AVG 백신",
    "brand": "AVG",
    "category": "etc",
    "fromUsd": 3.99,
    "skus": [
      {
        "label": "12 months",
        "months": 12,
        "usd": 46.99
      }
    ],
    "maxShare": 1,
    "features": [
      "AVG Ultimate 인터넷 보안",
      "랜섬웨어·멀웨어·해킹 차단",
      "VPN·안티트랙, 최대 10대 기기"
    ],
    "icon": "/icons/30.webp"
  },
  {
    "id": 32,
    "name": "스트라바(Strava)",
    "brand": "Strava",
    "category": "etc",
    "fromUsd": 4.99,
    "skus": [
      {
        "label": "12 months",
        "months": 12,
        "usd": 38.99
      }
    ],
    "maxShare": 1,
    "features": [
      "구간 경쟁·트레이닝 대시보드",
      "심박·파워 분석",
      "루트 계획·고급 지표"
    ],
    "icon": "/icons/32.jpg"
  }
];
